services:
  nodejs-server:
    image: mursaleennisar/express-vps
    deploy:
      replicas: 5
    networks:
      - node-internal

  caddy:
    image: caddy:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - node-internal

networks:
  node-internal:
    driver: bridge